modLoader = "javafml"
loaderVersion = "*"
license = "LGPL-3.0"

[[mods]]
modId = "yaclx"
version = "1.10"
displayName = "YetAnotherConfigLibExtensions"
authors = "Crendgrim"
description = '''
Utility Extensions to YetAnotherConfigLib
'''
logoFile = "icon.png"
displayTest = "IGNORE_ALL_VERSION"

[[dependencies.yaclx]]
modId = "neoforge"
mandatory = true
type = "required"
versionRange = "[20.3,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.yaclx]]
modId = "minecraft"
mandatory = true
type = "required"
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"
