modLoader = "javafml"
loaderVersion = "*"
license = "LGPL-3.0"

[[mods]]
modId = "libbamboo"
version = "1.13"
displayName = "libbamboo"
authors = "Crendgrim"
description = '''
Crendgrim's helper library
'''
logoFile = "icon.png"
displayTest = "IGNORE_ALL_VERSION"

[[dependencies.libbamboo]]
modId = "neoforge"
mandatory = true
type = "required"
versionRange = "[20.3,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.libbamboo]]
modId = "minecraft"
mandatory = true
type = "required"
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"
