modLoader = "javafml"
loaderVersion = "*"
license = "LGPL-3.0"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
authors = "Me"
description = "This is an example description! Tell everyone what your mod is about!"
logoFile = "assets/${id}/icon.png"
logoBlur = false

[[mixins]]
config = "libbamboo-common.mixins.json"

[[mixins]]
config = "libbamboo-neoforge.mixins.json"
