modLoader = "javafml"
loaderVersion = "*"
license = "LGPL-3.0"

[[mods]]
modId = "libbambootest"
version = "1.0"
displayName = "LibBambooTest"
authors = "Crendgrim"
description = '''
Test mod for LibBamboo
'''
logoFile = "icon.png"
displayTest = "IGNORE_ALL_VERSION"

[[dependencies.libbambootest]]
modId = "neoforge"
mandatory = true
type = "required"
versionRange = "[20.3,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.libbambootest]]
modId = "minecraft"
mandatory = true
type = "required"
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.libbambootest]]
modId = "libbamboo"
mandatory = true
type = "required"
versionRange = "[1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.libbambootest]]
modId = "yet_another_config_lib"
mandatory = false
type = "optional"
versionRange = "[3,)"
ordering = "NONE"
side = "BOTH"
